language: perl
perl:
  - "5.20"

before_install:
  #This should solve problem installing Perl's DB_File & GraphViz, needed for LaTeXML
  - "sudo apt-get update -qq"
  - "sudo apt-get install libdb-dev libxml2-dev libxslt1-dev 2>&1 | tail -n 4"